hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5d40cc77155b578d9b8cfa7ee37160212cf7bb4b7bc65f2743e370323644c6f6"

[[files]]
file = "mods/LuckPerms-Fabric-PlaceholderAPI-Hook.jar"
hash = "064b98c0979d28b282661156208e5bcba2e9a0c851b2e312e6f0042b94297687"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5086dbe83ed0c1032df18f5e054c789b044877bf5a8cf137243d7922768a266f"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "20ac4b3e8be440d9e7932d35127748f2908db186e352c2035e82eec929a018c3"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "ffcec38b71e8def4ec7e83a9e38f4c98999695b6bf0704a00a9c4cde9f96e613"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "b8a79212525cf4bd404890a8ec8ef86af1c45dd2fea90a09b41a73dfdfbaddf0"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "fc4da20f1beedc71997983f7b29309129fb2adaa955276af19c1064291c33112"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "7558b15bb58f0d6ed1c57a937829c4600d1df55dd95aae164fb35fd915c190b0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "98af3a5fd1d0bb5b5b30855280445fc8c64e3c9c5330bb6724c9ecc0029a809d"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "3a855e70564aea96fc1cb37786873421d0ffd1aa4f4e61b09b95104714dfb251"
metafile = true

[[files]]
file = "mods/cobbledollars.pw.toml"
hash = "6e3154e45d873d0f5040a07419617854b7b290caf0b78d26880b5db60bdd6b08"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "bb6a3413b81f6a8caba100a2b758fdaa2866dbc21a3e546dbdf31195e151290c"
metafile = true

[[files]]
file = "mods/cobblemon-badgebox.pw.toml"
hash = "19ef9d815721b66fb59d8d84cbce90cb21148ba5a83d1326d7cdd8f04ef15efd"
metafile = true

[[files]]
file = "mods/cobblemon-battle-extras.pw.toml"
hash = "b46635b8e2ff3e80b71918114ad4f4693d8415d90f009cff2c90b1e457204dde"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "219bec444d012e252d5dbf01595298cd43ad0cc1472f9300f817525b52ada3c9"
metafile = true

[[files]]
file = "mods/cobblemon-challenge.pw.toml"
hash = "b7c08009c2feffab111699afcb0acfe0412918ef4cbc91057a34e2a6edea243f"
metafile = true

[[files]]
file = "mods/cobblemon-firework-capsules.pw.toml"
hash = "91b45b59cf6350190aeb879ac816bde3cc464b4193998010e159a20d1f25368b"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "09e16803a1e2ab5e08df031a814ffd864d79d1d71647b55bb050147d3d8a52e2"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "4c43b2d10655a2ede98d8f0751cc30aa3ff30596f7b25ec7f76bbec267ebbeec"
metafile = true

[[files]]
file = "mods/cobblemon-paleontology.pw.toml"
hash = "24244325847dc7dc56ff496edf9f4013deba59128d622295bd5ea19e33acd1be"
metafile = true

[[files]]
file = "mods/cobblemon-pokemon-badges.pw.toml"
hash = "59291acd85d08fa4955d7549478c767f443904527b90dfbeca93006a7081e039"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "fc61506ebc44a6f70248be57260914122bfecd94f28efeb68e4468f0dcc14a8c"
metafile = true

[[files]]
file = "mods/cobblemon-spawn-notification.pw.toml"
hash = "3e50967987df075a40d40b331e3df69fbd09fa27a7dacda377176af7c3204c31"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
hash = "e959569778ca18fb3672aef764bd9c91b12244b639d3f5d7e6ed8eb8846e6f51"
metafile = true

[[files]]
file = "mods/cobblemon-utility+.pw.toml"
hash = "409c07e07766774f5e863f9f8f0cf48f5b2ace51e1d585fa1f694673df01b6ef"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "4905d15a09dbf7bbae4bef989c1cce526666cff25c82ae5994790813d8172151"
metafile = true

[[files]]
file = "mods/cobblemonboss.pw.toml"
hash = "17fc98a82288f504c69ca1531bf6e34605db0c3493f47a0640634b9eb03e3f41"
metafile = true

[[files]]
file = "mods/cobblemonextras.pw.toml"
hash = "e76e271b51587c2f6605c7cb57687f5f78fe634968bdce421643acf4fe0c7761"
metafile = true

[[files]]
file = "mods/cobblespawners.pw.toml"
hash = "f522b68f7943dd365c70d03a024aeb30a75271369685b59e7b295097a81abf47"
metafile = true

[[files]]
file = "mods/cobbreeding.pw.toml"
hash = "96f1d4a36968e3c259f063b79bab62689ab8b74c446b49ef2b8c230445a82fd9"
metafile = true

[[files]]
file = "mods/cyberanner-ironchest.pw.toml"
hash = "b4ac0540ee4a53abb31f935dce03b612069823d22f4d1fb902653864f019cfa2"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
hash = "5a42b13a84055aa5fc4991922853994803a3443bbaad3f21fa233991e98ee8e7"
metafile = true

[[files]]
file = "mods/e-utils.pw.toml"
hash = "f66f7332666086e04772a5b7cd7fdf9635c4d1a1b06a4266ffdb4c4102e32382"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "77a6bffed8925ae0f61061c14ba2a2504d9aa52647d4748c58708447f9381a1c"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "f879dc5dbb61d9c166045fc76c8513d732b70a23d8f0df9d72a66a0b0d8fa002"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "46452c8688316d63a81bad1c5e3e4c55c4db07418f9d9455981afe1c317d0fac"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "13389866198e1f1310cccf22f9160ea976340bd535b11b420097a3c50df3d6cf"
metafile = true

[[files]]
file = "mods/fabric-permissions-api.pw.toml"
hash = "7613801b3897e8d6beabf39adb85693159483d97e519628a16d2807761bb0d95"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
hash = "142e187aa7c3e74057da3650f40a0df528c04dc1768a5b11fd95fd3003e67232"
metafile = true

[[files]]
file = "mods/fastmove.pw.toml"
hash = "bd4ad98663ae79e78f1dd383128153196b4bea0e3b689ecbf2af75f30f4acdf5"
metafile = true

[[files]]
file = "mods/flan-cobblemon-extension.pw.toml"
hash = "77da8dcdbfab3a00d53f395098770afe91b31a764f19a69ab37bb8e1cf1ad922"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "d87437961334acdabc42c730ecd1597ef6437de63c0203d8df6351c72a23e423"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d52719e4ab00cfeaf30da28c8c0988d55f4c5d6cb417d81b06b3c1e959f9731b"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "570c7d292eb11dbdcf660866877c8fb1a460bed62f2bd2fe12a153353a232541"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "5b2399f142fbf4e880a9aaebc0da0447984062deb4845752b11ec6dd42e762c3"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "c4ee075c31686658020780a4f46f2c74064e84093c85fcf0525c2ca9a8ecfd00"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "87098120683099c085af035b2cd211e4f78c87283f7a4e7e41b69ae52dcd2ee1"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "4e955250202f44f8b876682834792ca98443fdefb30c0a308dcdabbe3bb8893d"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7799735ccd3d0278b77cce809c33fa7b9ca7dc48777d3332e4b16c576f099c91"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "a5d36dc6ea42390d604da5d2e8c934f5ca387bdaf015b72804e271a7b336ccb6"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "215f3a94df027c4a5a2ea4e6ae915a048494696a76a266fa6e8fba9ce12589ea"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "31b483c97f61b6f305cc6e5b9644da7ecfad37ee46d7f40d5bf1e3aa4ef1d7f7"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "74c9dfcdaea3c52915fe3b483f5679c2da9dd0a144fde4af704a756aae1f7213"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "0b9e9596514159e4e3f4b4e464b4ae7d13a0d1848a629586419b5c6e03d3ab87"
metafile = true

[[files]]
file = "mods/mighty-mail.pw.toml"
hash = "97c91db1e88a9d8d7584e5ded72016abb2511604d4ef70aadc92794f6dbc0fa5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a9063704df6c946c20e62f3ffbfacb54618253a77fa2357dbd6f72c6db2de8dc"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "83c375ab4b5374a2bed98f76b7085d168f23ddff991e22c3c31de079e9141f79"
metafile = true

[[files]]
file = "mods/navas-zamega.pw.toml"
hash = "67b46b8b2657de0c0996a76482cd64b6291c9edba5f52d2eb2dccb16b81e6609"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3b37cc60bbb73d9d37a9f6327db8b2a139b9f16771e38c01cfa111f106a7fdb0"
metafile = true

[[files]]
file = "mods/pokeblocks.pw.toml"
hash = "daa28fcd8e537e1e08274e8cacfc4bbf44040dadb7df8b0981c40aad36411bd6"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "ecc5e2446bb6c2b9eb288ad4efecc274631498cd4844dddf7ed985db6df05d3a"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "2e0f5793b364d7230031275a9abaa5d8c06e5bd88dbc1c764432ecc5729ab51e"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "fba2d74b05a6af1187d1e67bdd7a6dfdb5b2d270d90e2189811b93ee767bcf81"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "5db11a574dcc699ae274ce09b2a419b3cd47127d64e194e810257dbfaaec5a3e"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "6844e78f6d9131198963199fd4dc0d3072f167abd14a82c9750eed9e7e1d44c2"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "e9948fca8fcaf48d93795175c982391751c39948070d53ffb389208e4b8d3120"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "c0d9b2c0bcc1361c231490709cd4e2f035e18c1cc4b97707902418a235a986df"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c542328484e88993a84e7ff64402a25dadf3a56b70a2cdc54e2e8ece24616e1f"
metafile = true

[[files]]
file = "mods/tmcraft.pw.toml"
hash = "9bfc92516e6c78a2f1a9a3ea5f76d56ae7f042752fba4bcfd0ace2c3c0aeb044"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
hash = "389d02fe61354e23eb4c40db3c6aec50d978d1a968886e9cb0021eabe27d15e6"
metafile = true

[[files]]
file = "mods/travelers-backpack-fabric.pw.toml"
hash = "8092f0a5fca666fa7e3c13039fe0a0e67fc061fb13e01cb7c6b33d393f3c45dd"
metafile = true

[[files]]
file = "mods/vanilla-permissions.pw.toml"
hash = "b16b4fecae6e0425579b118cb97113fdcecc071fd658dbfe99f1ef97c9a16d00"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "ccdc34032afb46ea087d9e298dabdd625e7c3edb8ff8e8bc86967c44009478b9"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
hash = "d4254018d9beb74b016c902afd94c9e44f24fb74635c1abbf307bacf995b3dc6"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "72448c54b619e65b4c905afdf571545ae90fe4e3629202f6a79bb944082171a1"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "e8f69799f8525c70374bea8c0fb66a6357991fb0e980b49b17f51aaf3633a258"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "916728e497ca1b8b55aee7dd8ae9d147a7072b73dafcbc7e5b3997e52dfc2347"
metafile = true

[[files]]
file = "resourcepacks/A_ATM x MSD [3.1.2].zip"
hash = "3a49333d583a02835da474847736e34ed687be58d3f44db7a016352280c612fa"

[[files]]
file = "resourcepacks/B_CobbleCult Additions.zip"
hash = "51b61e4b82f144fc22055fe64c915d0b154f11874ac320e40fa097748b5cedb0"

[[files]]
file = "resourcepacks/C_Flower Expansion [CobbleCult Edition].zip"
hash = "6d0f41c7b7abd3e4fd2e78fa208ec432c2078cbac5351b90cac89b827e123df0"

[[files]]
file = "resourcepacks/Complete Galar Fossilmon E19 Icons.zip"
hash = "759d61973beb6966f8a1816cd9a73cb9e307ac84b73d201544aac574c518673c"

[[files]]
file = "resourcepacks/D_Carbink Gemstone Variations.zip"
hash = "f92f1a54aaea2033557896845e72178ddf9092666b2e16c676ff088de3923e87"

[[files]]
file = "resourcepacks/E_Rotom Appliances 1.2 [CobbleCult Edition].zip"
hash = "a93eb2079ee46d1e604c03c65fbc7c274697744b1f04bdcdcbe4a6fde879beab"

[[files]]
file = "resourcepacks/F_Dyable Mareep v1 [CobbleCult Edition].zip"
hash = "89235946992a2d46b4fbcc788c22d7269fb6d5ecd889c966fdfc5eafe1d5b5bb"

[[files]]
file = "resourcepacks/Flan's Cobblemon Extension.zip"
hash = "5c17e49eef9789aa39b90f563119ee5484d87ec2ff357bce01bf72fccd4d0c4d"

[[files]]
file = "resourcepacks/G_Complete Galar Fossilmon Addon.zip"
hash = "89bc569b86becc667ff732a9a67f11b95c9635ce95e17ad69639304789ef6f70"

[[files]]
file = "resourcepacks/H_Vivillon Pride Patterns v1.0.zip"
hash = "bc9576e55b02d4e15c5bb99b9b57f5f85cc2129d2d0dce890b7ea076d03a8bcb"

[[files]]
file = "resourcepacks/I_Shoulder Effects Remounted [CobbleCult Edition].zip"
hash = "17bf778431e5c1c0aeea0ee4ae8ca3f4570e6228cc50dfd927d9ea4f5c7fc297"

[[files]]
file = "resourcepacks/Z_CobbleCult x MSD Map Icons.zip"
hash = "c5c9e5c84873ddf29ec3c011d1d0f760f24b40db2aca62bded246aa190709f41"
