hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5d40cc77155b578d9b8cfa7ee37160212cf7bb4b7bc65f2743e370323644c6f6"

[[files]]
file = "mods/LuckPerms-Fabric-PlaceholderAPI-Hook.jar"
hash = "064b98c0979d28b282661156208e5bcba2e9a0c851b2e312e6f0042b94297687"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5285ba249b00d0d12a3cd1f64a5536e7618770dee31d3d240f9d4345ef69f888"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "5601649308a7d9f1658a942bbd48d3bd899a81fabd4ea1296952b48474d1ee1d"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "3e020f352ab64f88d0bbbee740ae1784d17b44337c02e2fd670889bbdbfa4a9a"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "1811ab4e8f2179c5661661c6aa47af90b5aa3d06d59601db1083c14314b137ea"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "56cd11a88ada9e8ef8614ce57f23db929b06579752ca4a1458dcfdf4a5aead9a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "5012b61748c44f005ae27692ef51484716c5df4cd9793a0df3fa6ce892f3e156"
metafile = true

[[files]]
file = "mods/cobbledollars.pw.toml"
hash = "25f8930a5814dfd54e697263a558293058e6c07603a44169b55e9fcea5ffd2e7"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "e4017e270ceacfe8dff8cdba6a657b903c002133a3bc88e8dbd54c6f55812b16"
metafile = true

[[files]]
file = "mods/cobblemon-badgebox.pw.toml"
hash = "dbcd6c1d82ef54574a85b8aa7a74d91cfbeca90830706346d2e1ee5bf2b9c86f"
metafile = true

[[files]]
file = "mods/cobblemon-battle-extras.pw.toml"
hash = "f18708955d182f8864c382b2a90047c558130891d66ba63f0b431223bd1ada3d"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "0b1740cc342248a7bf917a147d6b8e852a9253dfbcfe180f7cf50f97bf6d646e"
metafile = true

[[files]]
file = "mods/cobblemon-challenge.pw.toml"
hash = "218892097dfaab3452462623b504fbdc027a581acf335a37f9d4993f2fb0cb0a"
metafile = true

[[files]]
file = "mods/cobblemon-firework-capsules.pw.toml"
hash = "b694011058a0528888f239d63768157f9d124ab1ad7da9f4133b4a2ad5f16452"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "be97750e0c69d1650c3f679c61e0a14bc70f1bc0c13b6f6ac2681575fb4110dc"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "171759fbf6c75ae143c9f34173d814684a35a6dfe9f9042e8dc32792af696b7b"
metafile = true

[[files]]
file = "mods/cobblemon-paleontology.pw.toml"
hash = "b6285cd7cd6013d899e63ba53c2b7ee93662961d441c6d0ab7075994e1c4ade7"
metafile = true

[[files]]
file = "mods/cobblemon-pokemon-badges.pw.toml"
hash = "f9fca804b47d62948dc79c800723fa4e2e8d114171af6c19c901a59b99fbb073"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "eb51c053d004eafca2bca4cb91f9fedcee372fdf78c89fbbc6914c0fd103fc99"
metafile = true

[[files]]
file = "mods/cobblemon-spawn-notification.pw.toml"
hash = "33076e9cc6db7e0562434e37b9d9ff9da3ffb1af9eae9457649ad36211d6ae43"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
hash = "9e73dc663b6e07c0746087c337890b9c0354d05e2d15d51be154a9dac331566c"
metafile = true

[[files]]
file = "mods/cobblemon-utility+.pw.toml"
hash = "918ba57f88361c9915e487bef4bdb0608f82e996441820c1c153ad179934c7ad"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "6413f6c6bef7abc5a808a54111f093a17daf4471e89d8535840f2a24966bdcd4"
metafile = true

[[files]]
file = "mods/cobblemonboss.pw.toml"
hash = "f9d4415e42f796d19d1e37dbb5f804e8b55488b0dcb6f52f7153e21ea3ee394b"
metafile = true

[[files]]
file = "mods/cobblemonextras.pw.toml"
hash = "7ba736c8ac146c4e0cfaa2a96ff5e4e014b2d3a361b48394cd39a76cf3a515a4"
metafile = true

[[files]]
file = "mods/cobblespawners.pw.toml"
hash = "d65c20b4b5001b05bc098736e5356939d9a035fa4414c8b5a87f28e1f80552b6"
metafile = true

[[files]]
file = "mods/cobbreeding.pw.toml"
hash = "e1f7a7bc656fb2af171219849b67b26d496881ac5a4405573a122ad344441261"
metafile = true

[[files]]
file = "mods/cyberanner-ironchest.pw.toml"
hash = "6a89cf951df2610ceaf07877657de5ae63bf3bc67cc94f5d802c9cc78114fbf9"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
hash = "5c9f7094a4327e0730966e4a58617456695fbcbaedae3f79903ea6a1d939fc6e"
metafile = true

[[files]]
file = "mods/e-utils.pw.toml"
hash = "0477f41e688eb95d6106b4df2c4fd433023d0b36d1ee6aed1a4e885cb2d26716"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "4f128957cb3715a76e340e35273e9b38e474a0a3798a325f1b0a998db9d5c0c1"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "9642962bbcc8bfd0fc299df9858ba7e9ff8d25a6d69a6df976577d9cb219f442"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6ec22733a32cf6e59584fbf2a855e24ea2c05f46026e0799f34f34c0915c8367"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabric-permissions-api.pw.toml"
hash = "4f7bf8d60ef81f12471455f634bde52cc5a8c845250845b4519ad44ea46e61a6"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
hash = "5fe387bcad2d72c9bdd7047c19fed3959dcc65e2615e188ae743c517c08209df"
metafile = true

[[files]]
file = "mods/fastmove.pw.toml"
hash = "1c963bfb5a18f7a14ddf994b4071a135e190bd2e9cbdea99df5ab0697f8c1422"
metafile = true

[[files]]
file = "mods/flan-cobblemon-extension.pw.toml"
hash = "5fd289490e9dbc714c4cca3ce6757159720025af015a88ec86b0bba4bce6e3e1"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "3ef54c077956718ef1254d622d4202ac9f1156dd97a095695f20b23d2cbf3216"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d0e586bf4b4f9f003b1de1a3e18f67540233a0295b487009047056198f694f0f"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "73ba52fce9064dfb0a3b78f1d96354b79c52db7e2a3e8ecc713da6429b4c5723"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "fe2682e6dbdd4350863e1fcd3f5f211fb437cf7791539bedd50779745beb5232"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "00eaafc399810122b7522b172e12aec41f8d8b787192a78362f77e1274c21451"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "5aff706b484a368a4679b23cb2502154968b89251f17e0d4740ac189218c3dc7"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "515b020926d1fd0b6d1a32d106a376ba2c77bc5587bed99cecbc2d944ad18a99"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "37a45ed98e4edc9c8224cb06f72be8914fae69687601d4e15009f1cb9f27563c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5b8dfc9b7fda231ecb43ca1185c7f28ef9b4a0ed8c8df411ff7ad7b837817ee2"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "7438e773f85e37b376469cbe8749525e3353ff38711ddb3911dde77bbd0e3388"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f7cda152847b85f770b5130db1e1569b5b86ddf09d399377d7133365922a0e08"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "418dd349bc2f86a0725a9498684a7f87fcc4ae70e6f3967cb738ae133e996ec0"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "88b5510e39cdc8ca356d54bc436edc777d5eafc03203a8724784183408fe6792"
metafile = true

[[files]]
file = "mods/mighty-mail.pw.toml"
hash = "be23f8e39be6368729dc085d3443c8739092ad42df2740dca396b3914733c74c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "f85bbc82f8801b099dc53b89d5b52f9b4b9f364b746290c26f6e5447aaaa1db7"
metafile = true

[[files]]
file = "mods/navas-zamega.pw.toml"
hash = "0886ac3a006f1d4250738acdd5e77305e9babbe819a524fadb4700906cf2dab4"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/pokeblocks.pw.toml"
hash = "2776d6c14fbfbc55183ad6953596ae8e3cf35816813bf8d9cde663044d5c6121"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "1c13286be4f09e25c93ef1640335a951df1dd0f155f6d7a173dfc284831e09c3"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8deb4040131569c97902b40e0d81ef80330c6bb477c2ebcf5a5d987e1348eb96"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "090c32358b667855c299bad2592d85678a723f09cdeb36c76edd84ee08811744"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "81b8a1d186cc1685641bef736eadd143fa48909bd50cd7c975ec0d971a25e3ba"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "cbd24cdc5e83c7f687d56ed15b79f0e4ea890d9e825f747357e22831f67f4f0f"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "0e02e93b9468dca005f7fea385e92612e38bb6807f4dcd64ce7a4b22fac78581"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/tmcraft.pw.toml"
hash = "480dd12d946309eabf4fa0f01dd0a1c73efa3df5dddba36e23e4e47bc07e7400"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
hash = "b44e89cd6be4251903a0b128b0c49bb3dc5869159fe5ef273f441a0082ebe9fd"
metafile = true

[[files]]
file = "mods/travelers-backpack-fabric.pw.toml"
hash = "5f713fca609c017cb41162b503753a831f6f60b4e90a215c891544743c2a2a94"
metafile = true

[[files]]
file = "mods/vanilla-permissions.pw.toml"
hash = "9f3e865adc7318ec2072cd02a9d7f3dad9e4c1214249c04ebfdefcc39336b2e7"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "28d46dace618c4907d89e7041b37629ea21eab19af77b03f78cf5e0b8c32914b"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
hash = "242c7e1b0d9b33a7b5bca42b08c7931af304de816f7a6394baaddd35db0c4901"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "b408c5f1be6f3a0af123a351f4334e72d2ace21973096d7862243e109f28fbec"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "2b7f01bfe2ac36fefa911c2d6555b4d744110a29c9f967e8e07ff8a5a1de527c"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "1d0655bfbcbd799f0d44ab033aaf2c90950720cbb382c0210c6747bd2145dc62"
metafile = true

[[files]]
file = "resourcepacks/A_ATM x MSD [3.1.2].zip"
hash = "3a49333d583a02835da474847736e34ed687be58d3f44db7a016352280c612fa"

[[files]]
file = "resourcepacks/B_CobbleCult Additions.zip"
hash = "51b61e4b82f144fc22055fe64c915d0b154f11874ac320e40fa097748b5cedb0"

[[files]]
file = "resourcepacks/C_Flower Expansion [CobbleCult Edition].zip"
hash = "6d0f41c7b7abd3e4fd2e78fa208ec432c2078cbac5351b90cac89b827e123df0"

[[files]]
file = "resourcepacks/Complete Galar Fossilmon E19 Icons.zip"
hash = "759d61973beb6966f8a1816cd9a73cb9e307ac84b73d201544aac574c518673c"

[[files]]
file = "resourcepacks/D_Carbink Gemstone Variations.zip"
hash = "f92f1a54aaea2033557896845e72178ddf9092666b2e16c676ff088de3923e87"

[[files]]
file = "resourcepacks/E_Rotom Appliances 1.2 [CobbleCult Edition].zip"
hash = "a93eb2079ee46d1e604c03c65fbc7c274697744b1f04bdcdcbe4a6fde879beab"

[[files]]
file = "resourcepacks/F_Dyable Mareep v1 [CobbleCult Edition].zip"
hash = "89235946992a2d46b4fbcc788c22d7269fb6d5ecd889c966fdfc5eafe1d5b5bb"

[[files]]
file = "resourcepacks/Flan's Cobblemon Extension.zip"
hash = "5c17e49eef9789aa39b90f563119ee5484d87ec2ff357bce01bf72fccd4d0c4d"

[[files]]
file = "resourcepacks/G_Complete Galar Fossilmon Addon.zip"
hash = "89bc569b86becc667ff732a9a67f11b95c9635ce95e17ad69639304789ef6f70"

[[files]]
file = "resourcepacks/H_Vivillon Pride Patterns v1.0.zip"
hash = "bc9576e55b02d4e15c5bb99b9b57f5f85cc2129d2d0dce890b7ea076d03a8bcb"

[[files]]
file = "resourcepacks/I_Shoulder Effects Remounted [CobbleCult Edition].zip"
hash = "17bf778431e5c1c0aeea0ee4ae8ca3f4570e6228cc50dfd927d9ea4f5c7fc297"

[[files]]
file = "resourcepacks/Z_CobbleCult x MSD Map Icons.zip"
hash = "c5c9e5c84873ddf29ec3c011d1d0f760f24b40db2aca62bded246aa190709f41"
