hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5d40cc77155b578d9b8cfa7ee37160212cf7bb4b7bc65f2743e370323644c6f6"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5285ba249b00d0d12a3cd1f64a5536e7618770dee31d3d240f9d4345ef69f888"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "93f989575eec26f333d4253f1af961983ba4d5179e1c3237b643836b40614a43"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "441cdd198ab71062744936c7ce2eabcbd93c98d92e805c5dcfacf8a7a6fb8ede"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "b4c91be6e9a39270e4befd5feac995faa644c2b44f583a6a97b62032eb2e9599"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "5cdc5287bd9b90d0838285a5be293ef46f93058e356821c0c8ee1354e160387e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c71a57581893de5538e21bc2b2b1946ff2e1f8d6f6f3ab558556dcf813b84ba7"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "5012b61748c44f005ae27692ef51484716c5df4cd9793a0df3fa6ce892f3e156"
metafile = true

[[files]]
file = "mods/cobbledollars.pw.toml"
hash = "25f8930a5814dfd54e697263a558293058e6c07603a44169b55e9fcea5ffd2e7"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "e4017e270ceacfe8dff8cdba6a657b903c002133a3bc88e8dbd54c6f55812b16"
metafile = true

[[files]]
file = "mods/cobblemon-badgebox.pw.toml"
hash = "dbcd6c1d82ef54574a85b8aa7a74d91cfbeca90830706346d2e1ee5bf2b9c86f"
metafile = true

[[files]]
file = "mods/cobblemon-battle-extras.pw.toml"
hash = "f18708955d182f8864c382b2a90047c558130891d66ba63f0b431223bd1ada3d"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "0b1740cc342248a7bf917a147d6b8e852a9253dfbcfe180f7cf50f97bf6d646e"
metafile = true

[[files]]
file = "mods/cobblemon-challenge.pw.toml"
hash = "63487e345c0b3ad6693ff6a006032462886c2f6b294898ad82efa88a7cf4302b"
metafile = true

[[files]]
file = "mods/cobblemon-firework-capsules.pw.toml"
hash = "b694011058a0528888f239d63768157f9d124ab1ad7da9f4133b4a2ad5f16452"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "be97750e0c69d1650c3f679c61e0a14bc70f1bc0c13b6f6ac2681575fb4110dc"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "171759fbf6c75ae143c9f34173d814684a35a6dfe9f9042e8dc32792af696b7b"
metafile = true

[[files]]
file = "mods/cobblemon-paleontology.pw.toml"
hash = "b6285cd7cd6013d899e63ba53c2b7ee93662961d441c6d0ab7075994e1c4ade7"
metafile = true

[[files]]
file = "mods/cobblemon-pokemon-badges.pw.toml"
hash = "f9fca804b47d62948dc79c800723fa4e2e8d114171af6c19c901a59b99fbb073"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "eb51c053d004eafca2bca4cb91f9fedcee372fdf78c89fbbc6914c0fd103fc99"
metafile = true

[[files]]
file = "mods/cobblemon-spawn-notification.pw.toml"
hash = "fcae16c281a1fce8c440f65e333fdd318a7f738dd41c9102cf76f649968d2d97"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
hash = "d4209af3e46ad2c248598c3d09e00325752f05464d43a57b1178669efafb2670"
metafile = true

[[files]]
file = "mods/cobblemon-utility+.pw.toml"
hash = "918ba57f88361c9915e487bef4bdb0608f82e996441820c1c153ad179934c7ad"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "6413f6c6bef7abc5a808a54111f093a17daf4471e89d8535840f2a24966bdcd4"
metafile = true

[[files]]
file = "mods/cobblemonboss.pw.toml"
hash = "a196030b1f10830572474653d782ac347944e823c9c13689cc8ed68034500d7c"
metafile = true

[[files]]
file = "mods/cobblemonextras.pw.toml"
hash = "7ba736c8ac146c4e0cfaa2a96ff5e4e014b2d3a361b48394cd39a76cf3a515a4"
metafile = true

[[files]]
file = "mods/cobblespawners.pw.toml"
hash = "d65c20b4b5001b05bc098736e5356939d9a035fa4414c8b5a87f28e1f80552b6"
metafile = true

[[files]]
file = "mods/cobbreeding.pw.toml"
hash = "e1f7a7bc656fb2af171219849b67b26d496881ac5a4405573a122ad344441261"
metafile = true

[[files]]
file = "mods/cyberanner-ironchest.pw.toml"
hash = "6a89cf951df2610ceaf07877657de5ae63bf3bc67cc94f5d802c9cc78114fbf9"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
hash = "5c9f7094a4327e0730966e4a58617456695fbcbaedae3f79903ea6a1d939fc6e"
metafile = true

[[files]]
file = "mods/e-utils.pw.toml"
hash = "0477f41e688eb95d6106b4df2c4fd433023d0b36d1ee6aed1a4e885cb2d26716"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "4f128957cb3715a76e340e35273e9b38e474a0a3798a325f1b0a998db9d5c0c1"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "9642962bbcc8bfd0fc299df9858ba7e9ff8d25a6d69a6df976577d9cb219f442"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6ec22733a32cf6e59584fbf2a855e24ea2c05f46026e0799f34f34c0915c8367"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabric-permissions-api.pw.toml"
hash = "4f7bf8d60ef81f12471455f634bde52cc5a8c845250845b4519ad44ea46e61a6"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
hash = "45906e2c93c55ffdf72bd3d4a306bcda58933b3c42c9a57d8866a0220a36083d"
metafile = true

[[files]]
file = "mods/fastmove.pw.toml"
hash = "1c963bfb5a18f7a14ddf994b4071a135e190bd2e9cbdea99df5ab0697f8c1422"
metafile = true

[[files]]
file = "mods/flan-cobblemon-extension.pw.toml"
hash = "5fd289490e9dbc714c4cca3ce6757159720025af015a88ec86b0bba4bce6e3e1"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "8c7023170f349c3bee0bb15197d280158d7990a3adffcbf0eb766f2c0f257fc5"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "937e6ea5f6b4a89b2c21495c05c1d8a35d2abcfa8c544a314cbb886fc2a83bec"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "da4e93721fe3bad889f369636f1abd616954a4faefe8d73f1ebd739b718d490f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "fe2682e6dbdd4350863e1fcd3f5f211fb437cf7791539bedd50779745beb5232"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "cd8e6d4a28f826e87afebd58b93338f9411fcfd3cc8dbb532b961e6060a084cd"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "2baa05930efe0e1c18f25f33aa079e39878bdf0930fc1fcb4e0c628b4f42e7c2"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "515b020926d1fd0b6d1a32d106a376ba2c77bc5587bed99cecbc2d944ad18a99"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "37a45ed98e4edc9c8224cb06f72be8914fae69687601d4e15009f1cb9f27563c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "9993ba04580da7893f9f6289981659c29d6a04de5b29007c7c8c9f7846d8480c"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "917affe7e27c3408aa5bf5b255c5222973fd1823cb9c733169109c7a861c48f8"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c11e65ca1d8bcb5f1a724054300119bbc4e9a5f56707f91083e612410a0ff412"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "418dd349bc2f86a0725a9498684a7f87fcc4ae70e6f3967cb738ae133e996ec0"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "88b5510e39cdc8ca356d54bc436edc777d5eafc03203a8724784183408fe6792"
metafile = true

[[files]]
file = "mods/mighty-mail.pw.toml"
hash = "56b37fb71781d82b8c026273b7d2e0524ed2cdd7d659bb6e67118d64680eb4ef"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c9cc1728ca3d16e37afe3db4a65e63cdcf90d759ae36e633cb0ebf18ee47c336"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "ef64b5ce621de05f79ea518bc6de198f420b0c925c012c0864611cb162019c47"
metafile = true

[[files]]
file = "mods/navas-zamega.pw.toml"
hash = "0886ac3a006f1d4250738acdd5e77305e9babbe819a524fadb4700906cf2dab4"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/pokeblocks.pw.toml"
hash = "2776d6c14fbfbc55183ad6953596ae8e3cf35816813bf8d9cde663044d5c6121"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "98da190eb33a9f81e8f135e755b3c2dea15de442ae29a4959976812a8d880fed"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ccec1d3f514f6e031446c4011fc546b2760a32e1f9e14b04a56ddd56fd5b3633"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "553b0820c73dd0b3bec79a93a4f8c70ce327c8f7f6e2226bbd73cd92329b61c5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f03452b38a7ce73431c647b772f11051d30bb23891f6dfba1173a65319f4d7ac"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "81b8a1d186cc1685641bef736eadd143fa48909bd50cd7c975ec0d971a25e3ba"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "cbd24cdc5e83c7f687d56ed15b79f0e4ea890d9e825f747357e22831f67f4f0f"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "327da625b2bea6a8e54e4a4448e4956691c8d0fcbfffc03da9025cc02c3456b5"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "e4608bc421ac3e204937b9943a0c23ce8be98e9fee1b846acf3da58898dacf70"
metafile = true

[[files]]
file = "mods/tmcraft.pw.toml"
hash = "480dd12d946309eabf4fa0f01dd0a1c73efa3df5dddba36e23e4e47bc07e7400"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
hash = "b44e89cd6be4251903a0b128b0c49bb3dc5869159fe5ef273f441a0082ebe9fd"
metafile = true

[[files]]
file = "mods/travelers-backpack-fabric.pw.toml"
hash = "b0258c29bf5d2255c7576c88d5537fbd32a834510b04b6e36b151131b259fd74"
metafile = true

[[files]]
file = "mods/vanilla-permissions.pw.toml"
hash = "9f3e865adc7318ec2072cd02a9d7f3dad9e4c1214249c04ebfdefcc39336b2e7"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "28d46dace618c4907d89e7041b37629ea21eab19af77b03f78cf5e0b8c32914b"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
hash = "b90d23d200040dedec39d025bad5c3b70387522f5612aa79bbfd4d281ed457b6"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "b034f5d5354c16f9e2a7607984fc55c5938111053f390dd51b2e621e912447e8"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "bb624f59fa32ce41654df7534756cf856d77540981754568b81712440d696e55"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "387895f19cc7f3e256afa22c9354120c1c3695846356caf72651229cfefeab5a"
metafile = true

[[files]]
file = "resourcepacks/A_ATM x MSD [3.1.2].zip"
hash = "3a49333d583a02835da474847736e34ed687be58d3f44db7a016352280c612fa"

[[files]]
file = "resourcepacks/B_CobbleCult Additions.zip"
hash = "51b61e4b82f144fc22055fe64c915d0b154f11874ac320e40fa097748b5cedb0"

[[files]]
file = "resourcepacks/C_Flower Expansion [CobbleCult Edition].zip"
hash = "6d0f41c7b7abd3e4fd2e78fa208ec432c2078cbac5351b90cac89b827e123df0"

[[files]]
file = "resourcepacks/Complete Galar Fossilmon E19 Icons.zip"
hash = "759d61973beb6966f8a1816cd9a73cb9e307ac84b73d201544aac574c518673c"

[[files]]
file = "resourcepacks/D_Carbink Gemstone Variations.zip"
hash = "f92f1a54aaea2033557896845e72178ddf9092666b2e16c676ff088de3923e87"

[[files]]
file = "resourcepacks/E_Rotom Appliances 1.2 [CobbleCult Edition].zip"
hash = "a93eb2079ee46d1e604c03c65fbc7c274697744b1f04bdcdcbe4a6fde879beab"

[[files]]
file = "resourcepacks/F_Dyable Mareep v1 [CobbleCult Edition].zip"
hash = "89235946992a2d46b4fbcc788c22d7269fb6d5ecd889c966fdfc5eafe1d5b5bb"

[[files]]
file = "resourcepacks/Flan's Cobblemon Extension.zip"
hash = "5c17e49eef9789aa39b90f563119ee5484d87ec2ff357bce01bf72fccd4d0c4d"

[[files]]
file = "resourcepacks/G_Complete Galar Fossilmon Addon.zip"
hash = "89bc569b86becc667ff732a9a67f11b95c9635ce95e17ad69639304789ef6f70"

[[files]]
file = "resourcepacks/H_Vivillon Pride Patterns v1.0.zip"
hash = "bc9576e55b02d4e15c5bb99b9b57f5f85cc2129d2d0dce890b7ea076d03a8bcb"

[[files]]
file = "resourcepacks/I_Shoulder Effects Remounted [CobbleCult Edition].zip"
hash = "17bf778431e5c1c0aeea0ee4ae8ca3f4570e6228cc50dfd927d9ea4f5c7fc297"

[[files]]
file = "resourcepacks/Z_CobbleCult x MSD Map Icons.zip"
hash = "c5c9e5c84873ddf29ec3c011d1d0f760f24b40db2aca62bded246aa190709f41"
